# Generated by Django 5.1 on 2024-09-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='order_status',
            field=models.CharField(choices=[('', 'Select the catagaroies'), ('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=10),
        ),
    ]
