# Generated by Django 5.1 on 2024-09-14 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Buy.buy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('', 'Select the catagaroies'), ('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=10),
        ),
    ]
