# Generated by Django 5.1 on 2024-09-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.BigIntegerField()),
                ('item_description', models.TextField(blank=True, max_length=500, null=True)),
                ('item_tag', models.CharField(max_length=10, unique=True)),
                ('item_type', models.CharField(blank=True, choices=[('', 'select the choice'), ('F', 'Fashion'), ('A', 'Appliances'), ('G', 'grocerys')], max_length=10, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
